name: Update Formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (without v prefix)'
        required: true
      sha256:
        description: 'SHA256 of the release tarball'
        required: true

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Update Formula
        run: |
          # Extract version and SHA256 from inputs
          VERSION="${{ github.event.inputs.version }}"
          SHA256="${{ github.event.inputs.sha256 }}"
          
          # Update the formula
          sed -i "s|url \".*\"|url \"https://github.com/dikaio/scribe/archive/refs/tags/v${VERSION}.tar.gz\"|" Formula/scribe.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|" Formula/scribe.rb
          
          # Commit the changes
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/scribe.rb
          git commit -m "Update scribe to v${VERSION}"
          git push